name: Build & Push Naming Server

on:
  push:
    branches:
      - main
    paths:
      - 'naming-server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./naming-server
          file: ./naming-server/Dockerfile
          push: true
          tags: marijancastvan/naming-server:latest
